# Transposed Convolutions (inappropriately called ''deconvolutions'')
https://pytorch.org/docs/stable/nn.html#torch.nn.ConvTranspose2d  
https://towardsdatascience.com/types-of-convolutions-in-deep-learning-717013397f4d

In [1]:
import numpy as np
import torch

def describe(a):
    print(a)
    print(a.shape)
    print(a.dtype)

In [2]:
x = torch.FloatTensor([[[[1, 2], [3, 4]]]])
describe(x)

tensor([[[[1., 2.],
          [3., 4.]]]])
torch.Size([1, 1, 2, 2])
torch.float32


In [3]:
w = torch.ones([1, 1, 2, 2])
describe(w)

tensor([[[[1., 1.],
          [1., 1.]]]])
torch.Size([1, 1, 2, 2])
torch.float32


In [4]:
z1 = torch.nn.functional.conv_transpose2d(x, w)
describe(z1)

tensor([[[[ 1.,  3.,  2.],
          [ 4., 10.,  6.],
          [ 3.,  7.,  4.]]]])
torch.Size([1, 1, 3, 3])
torch.float32


In [5]:
z2 = torch.nn.functional.conv_transpose2d(x, w, stride=2)
describe(z2)

tensor([[[[1., 1., 2., 2.],
          [1., 1., 2., 2.],
          [3., 3., 4., 4.],
          [3., 3., 4., 4.]]]])
torch.Size([1, 1, 4, 4])
torch.float32


In [6]:
z3 = torch.nn.functional.conv_transpose2d(x, w, stride=3)
describe(z3)

tensor([[[[1., 1., 0., 2., 2.],
          [1., 1., 0., 2., 2.],
          [0., 0., 0., 0., 0.],
          [3., 3., 0., 4., 4.],
          [3., 3., 0., 4., 4.]]]])
torch.Size([1, 1, 5, 5])
torch.float32
