In [1]:
# the distance between all pairs of points in a given set
import numpy as np
from scipy.spatial.distance import pdist, squareform

# Create the following array where each row is a point in 2D space:
# [[0 1]
#  [1 0]
#  [2 0]]
x = np.array([[0, 1], [1, 0], [2, 0]])
print(x)

# Compute the Euclidean distance between all rows of x.
# d[i, j] is the Euclidean distance between x[i, :] and x[j, :],
# and d is the following array:
# [[ 0.          1.41421356  2.23606798]
#  [ 1.41421356  0.          1.        ]
#  [ 2.23606798  1.          0.        ]]
d = squareform(pdist(x, 'euclidean'))
print(d)

[[0 1]
 [1 0]
 [2 0]]
[[ 0.          1.41421356  2.23606798]
 [ 1.41421356  0.          1.        ]
 [ 2.23606798  1.          0.        ]]


In [2]:
# the distance between all pairs of points in a given set
import numpy as np
from scipy.spatial.distance import pdist, squareform

x = np.array([[0, 1], [7, 0], [2, 0], [40, 3]])
print('initial points')
print(x)

print('\npdist')
print(pdist(x, 'euclidean'))

d = squareform(pdist(x, 'euclidean'))
print('\nsquareform(pdist(..))')
print(d)

initial points
[[ 0  1]
 [ 7  0]
 [ 2  0]
 [40  3]]

pdist
[  7.07106781   2.23606798  40.04996879   5.          33.13608305
  38.11823711]

squareform(pdist(..))
[[  0.           7.07106781   2.23606798  40.04996879]
 [  7.07106781   0.           5.          33.13608305]
 [  2.23606798   5.           0.          38.11823711]
 [ 40.04996879  33.13608305  38.11823711   0.        ]]


In [3]:
# the distance between all pairs across two sets of points
import numpy as np
from scipy.spatial.distance import cdist

a = np.array([[1, 0], [0, -7], [4, 6]])
b = np.array([[-2, 4], [0, 0], [2, 2], [3, 9]])

print(cdist(a, b, 'euclidean'))

[[  5.           1.           2.23606798   9.21954446]
 [ 11.18033989   7.           9.21954446  16.2788206 ]
 [  6.32455532   7.21110255   4.47213595   3.16227766]]


In [4]:
# the distance between all pairs across two sets of points
import numpy as np
from scipy.spatial.distance import cdist

a = np.array([[1, 0], [0, -7], [4, 6]])
b = np.array([[-2, 4], [0, 0], [2, 2], [3, 9]])

print(cdist(a, b, lambda u, v: np.sqrt(((u - v) ** 2).sum())))

[[  5.           1.           2.23606798   9.21954446]
 [ 11.18033989   7.           9.21954446  16.2788206 ]
 [  6.32455532   7.21110255   4.47213595   3.16227766]]


In [5]:
# the distance between all pairs across two sets of points
import numpy as np
from scipy.spatial.distance import cdist

print(cdist([[0, 1]], [[4, 4]], 'euclidean'))

[[ 5.]]
