In [1]:
import numpy as np

a = np.array([1, 2, 3])
print(type(a))
print(a)
print(a[0], a[1], a[2])

print(a.shape) # (3,)
print(a.size)  # 3

# a.ndim == len(a.shape)
print(len(a.shape)) # 1
print(a.ndim)       # 1


<type 'numpy.ndarray'>
[1 2 3]
(1, 2, 3)
(3,)
3
1
1


In [2]:
import numpy as np

b = np.array([[1, 2, 3], [4, 5, 6]])
print(b[0])
print(b[1])
print(b[0, 0], b[0, 1], b[1, 0])

print(b.shape) # (2, 3)
print(b.size)  # 6

# b.ndim == len(b.shape)
print(len(b.shape)) # 2
print(b.ndim)       # 2

[1 2 3]
[4 5 6]
(1, 2, 4)
(2, 3)
6
2
2


In [3]:
import numpy as np

a = np.zeros((2))
print(a)

a = np.zeros((3, 5))
print(a)

b = np.ones((1, 4))
print(b)

c = np.full((2, 3), 7)
c[0, 2] = 4
print(c)

d = np.eye(3)
print(d)

d = np.eye(2, 5)
print(d)

e = np.random.random((2, 3))
print(e)

[ 0.  0.]
[[ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]]
[[ 1.  1.  1.  1.]]
[[7 7 4]
 [7 7 7]]
[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]
[[ 1.  0.  0.  0.  0.]
 [ 0.  1.  0.  0.  0.]]
[[ 0.38160191  0.51022753  0.93551151]
 [ 0.33649423  0.99197485  0.58733583]]


In [4]:
import numpy as np

a = np.arange(10)
print(a)

b = np.arange(2, 10, dtype=float)
print(b)

c = np.arange(2, 3, 0.1)
print(c)

[0 1 2 3 4 5 6 7 8 9]
[ 2.  3.  4.  5.  6.  7.  8.  9.]
[ 2.   2.1  2.2  2.3  2.4  2.5  2.6  2.7  2.8  2.9]


In [5]:
import numpy as np

x = np.linspace(1, 5, 9)
print(x)

[ 1.   1.5  2.   2.5  3.   3.5  4.   4.5  5. ]
