In [1]:
# slicing
import numpy as np

x = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
print(x[1:7:2]) # Prints "[1 3 5]"

[1 3 5]


In [2]:
import numpy as np

a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
b = a[:2, 1:3]

# A slice of an array is a view into the same data, so modifying it
# will modify the original array
print(a[0, 1]) # Prints "2"
b[0, 0] = 77   # b[0, 0] is the same piece of data as a[0, 1]
print(a[0, 1]) # Prints "77

2
77


In [3]:
import numpy as np

a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

# Two ways of accesing the data in the middle row of the array.
# Mixing integer indexing with slices yields an array of lower rank,
# while using only slices yields an array of the same rank as the
# original array:
row_r1 = a[1, :]   # Rank 1 view of the second row of a
row_r2 = a[1:2, :] # Rank 2 view of the second row of a
print(row_r1, row_r1.shape) # Prints "[5 6 7 8] (4,)"
print(row_r2, row_r2.shape) # Prints "[[5 6 7 8]] (1, 4)"

# We can make the same distinction when accessing columns of an array:
col_r1 = a[:, 1]
col_r2 = a[:, 1:2]
print(col_r1, col_r1.shape) # Prints "[2 6 10] (3,)"
print(col_r2, col_r2.shape) # Prints "[[2]
                            #          [6]
                            #          [10]] (1, 3)"

(array([5, 6, 7, 8]), (4,))
(array([[5, 6, 7, 8]]), (1, 4))
(array([ 2,  6, 10]), (3,))
(array([[ 2],
       [ 6],
       [10]]), (3, 1))


In [4]:
# integer array indexing
import numpy as np

a = np.array([[1, 2], [3, 4], [5, 6]])

# These examples are equivalent
# Both print "[1 4 5]"
print(a[[0, 1, 2], [0, 1, 0]]) 
print(np.array([a[0, 0], a[1, 1], a[2, 0]]))

# The same happens here
# Both print "[2, 2]"
# You can reuse the same element from the source array
print(a[[0, 0], [1, 1]])
print(np.array([a[0, 1], a[0, 1]]))

[1 4 5]
[1 4 5]
[2 2]
[2 2]


In [5]:
import numpy as np

a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])

print(a)

# Array of indices
b = np.array([0, 2, 0, 1])

# Select one element from each row of a using the indices in b
print(a[np.arange(4), b])

# Mutate one element from each row of a using the indices in b
a[np.arange(4), b] += 10

print(a)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[ 1  6  7 11]
[[11  2  3]
 [ 4  5 16]
 [17  8  9]
 [10 21 12]]


In [6]:
# boolean indexing
import numpy as np

a = np.array([[-1, 2], [3, -4], [0, 6]])

bool_idx = (a > 2)   # Find the elements of a that are bigger than 2;
                     # this returns a numpy array of Booleans of the same
                     # shape as a, where each slot of bool_idx tells
                     # whether that element of a is > 2.

print(bool_idx)      # Prints "[[False False]
                     #          [ True  False]
                     #          [ False  True]]"

# We use boolean array indexing to construct a rank 1 array
# consisting of the elements of a corresponding to the True values
# of bool_idx
print(a[bool_idx])  # Prints "[3 6]"

# We can do all of the above in a single concise statement:
print(a[a > 2])     # Prints "[3 6]"

[[False False]
 [ True False]
 [False  True]]
[3 6]
[3 6]
