In [1]:
import numpy as np

x = np.array([[1, 2], [3, 4]], dtype=np.float64)
y = np.array([[5, 6], [7, 8]], dtype=np.float64)

# Elementwise sum
print(x + y)
print(np.add(x, y))

# Elementwise difference
print(x - y)
print(np.subtract(x, y))

# Elementwise product
print(x * y)
print(np.multiply(x, y))

# Elementwise division
print(x / y)
print(np.divide(x, y))

# Elementwise square root
print(np.sqrt(x))

[[  6.   8.]
 [ 10.  12.]]
[[  6.   8.]
 [ 10.  12.]]
[[-4. -4.]
 [-4. -4.]]
[[-4. -4.]
 [-4. -4.]]
[[  5.  12.]
 [ 21.  32.]]
[[  5.  12.]
 [ 21.  32.]]
[[ 0.2         0.33333333]
 [ 0.42857143  0.5       ]]
[[ 0.2         0.33333333]
 [ 0.42857143  0.5       ]]
[[ 1.          1.41421356]
 [ 1.73205081  2.        ]]


In [2]:
import numpy as np

x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6], [7, 8]])

v = np.array([9, 10])
w = np.array([11, 12])

# Inner product of vectors
# Both produce 219
print(v.dot(w))
print(np.dot(v, w))

# Matrix / vector product
# Both produce the rank 1 array [29 67]
print(x.dot(v))
print(np.dot(x, v))

# Matrix / matrix product
# Both produce the rank 2 array
# [[19 22]
#  [43 50]]
print(x.dot(y))
print(np.dot(x, y))

219
219
[29 67]
[29 67]
[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


In [3]:
import numpy as np

x = np.array([[1, 2], [3, 4]])

print(np.sum(x))         # 10 (sum of all elements)
print(np.sum(x, axis=0)) # [4 6] (sum of each column)
print(np.sum(x, axis=1)) # [3 7] (sum of each row)

10
[4 6]
[3 7]


In [4]:
import numpy as np

x = np.array([[1, 2], [3, 4]])

print(np.prod(x))         # 24 (product of all elements)
print(np.prod(x, axis=0)) # [3 8]  (product of each column)
print(np.prod(x, axis=1)) # [2 12] (product of each row)

24
[3 8]
[ 2 12]


In [5]:
import numpy as np

x = np.array([[1, 2], [3, 4]])

print(x)
print(x.T) # the transpose of x

# Taking the transpose of a rank 1 array does nothing:
v = np.array([1, 2, 3])
print(v)
print(v.T)

[[1 2]
 [3 4]]
[[1 3]
 [2 4]]
[1 2 3]
[1 2 3]


In [6]:
import numpy as np

x = np.array([[1, 2], [3, 4]])

print(x.flatten())

[1 2 3 4]
