In [1]:
import numpy as np

from pprint import pprint

## Array indexing  
_Numpy_ offers several ways to index into arrays. I will mention some methods of indexing.  
More information can be found here: http://cs231n.github.io/python-numpy-tutorial/#numpy-array-indexing  

Example: a is the following rank 2 array:  
[[ 0  1  2  3  4]  
 [ 5  6  7  8  9]  
 [10 11 12 13 14]]  

1.) __Slicing__: 
   * specify a slice for each dimension of the array;
   * the result will be an array with the same rank (nr of dimensions).
   
   > a[:, 1:4] -> array([[1, 2, 3], [6, 7, 8], [11, 12, 13]])  
   
2.) __Integer indexing__:
   * specify lists of indices for each dimension of the array;
   * the result will be an array with a lower rank (nr of dimensions).
   
   > a[range(3), range(1, 4)] -> array([1, 7, 13])  
   > a[[0, 1, 2], [1, 2, 3]]  -> array([1, 7, 13]) 

3.) __Integer indexing + slicing => slicing behaviour__
   * the result will be an array with the same rank.
   
   > a[[0, 1, 2], 1:4]  -> array([[1, 2, 3], [6, 7, 8], [11, 12, 13]])  

In [2]:
a = np.arange(15).reshape(3, 5)
print(type(a))
print(a.shape)
print(a)

<type 'numpy.ndarray'>
(3, 5)
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [3]:
# slicing
print(a[:, 1:4].shape)
print(a[:, 1:4])
print(a[0:3, 1:4].shape)
print(a[0:3, 1:4])

(3, 3)
[[ 1  2  3]
 [ 6  7  8]
 [11 12 13]]
(3, 3)
[[ 1  2  3]
 [ 6  7  8]
 [11 12 13]]


In [4]:
# integer indexing
print(a[range(3), range(1, 4)].shape)
print(a[range(3), range(1, 4)])

print(a[[0, 1, 2], [1, 2, 3]].shape)
print(a[[0, 1, 2], [1, 2, 3]])

(3,)
[ 1  7 13]
(3,)
[ 1  7 13]


In [5]:
# integer indexing + slicing => slicing behaviour
print(a[[0, 1, 2], 1:4].shape)
print(a[[0, 1, 2], 1:4])
print(a[0:3, [1, 2, 3]].shape)
print(a[0:3, [1, 2, 3]])

(3, 3)
[[ 1  2  3]
 [ 6  7  8]
 [11 12 13]]
(3, 3)
[[ 1  2  3]
 [ 6  7  8]
 [11 12 13]]


In [6]:
print(type(a[1]))

print(a[1].shape)
print(a[1])
print(a[1, :].shape)
print(a[1, :])
print(a[1, np.arange(a.shape[1])].shape)
print(a[1, np.arange(a.shape[1])])

<type 'numpy.ndarray'>
(5,)
[5 6 7 8 9]
(5,)
[5 6 7 8 9]
(5,)
[5 6 7 8 9]


In [7]:
print(type(a[1, :, np.newaxis]))

print(a[1, :, np.newaxis].shape)
print(a[1, :, np.newaxis])

print(a[np.newaxis, 1, :].shape)
print(a[np.newaxis, 1, :])

<type 'numpy.ndarray'>
(5, 1)
[[5]
 [6]
 [7]
 [8]
 [9]]
(1, 5)
[[5 6 7 8 9]]


In [8]:
print(a)
print(a[:, [3, 3]])

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
[[ 3  3]
 [ 8  8]
 [13 13]]
